### PR TITLE
Chore(ember-cli): Update to version 2.10.1

### LINKED ISSUE #11: revisions.json is empty after deploy
@arenoir I'm on a bad internet connection and it seems that the plugin isn't waiting for the tasks to finish. Haven't found the source of the problem but it looks like some of the methods don't return a promise causing ember-cli-deploy to not wait until the work is done. Are you still maintaining the plugin? I would dig into it and send a PR. I think that would solve #8 as well.

### PR DESCRIPTION
**Pull request by fsmanuel**
@arenoir to make it easier I update ember-cli to version 2.10.1
The follow up PR to fix #11 will come as soon as I have time.

### CODE REVIEW

**Comment by arenoir** [comment]
@fsmanuel, thanks for the pr. Were you able to get the test suit to run?  I don't think it is necessary to use ember-try for ember-cli-deploy plugins.

**Comment by fsmanuel** [comment]
@arenoir will check.

**Comment by fsmanuel** [comment]
@arenoir Tests are running now and I squash the commits.

**Comment by arenoir** [comment]
@fsmanuel... looks good

**Pull request merged**
